/**
 * Type definitions for the video / image asset manifest stored on R2 CDN.
 *
 * Source of truth: video-manifest.json on R2 (https://media.novameapp.com/video-manifest.json)
 *
 * Schema generated by scripts run during stage 3.3.A.3. Do not edit
 * manifest fields without updating the generator + re-uploading the
 * manifest to R2.
 */

export type ManifestVersion = 'v1';

export type VideoOutfitState = 'chill' | 'hungry' | 'study';

export type CardCategory = 'mind' | 'heart' | 'action' | 'connection';

export type CardType = 'front' | 'back';

/**
 * A single character animation video (e.g. char1-outfit1-chill.mp4).
 *
 * Naming convention: char{characterNum}-outfit{N}-{state}.mp4
 * Currently only character 1 (char1), outfits 1-6, 3 states each = 18 total.
 */
export type VideoManifestEntry = {
  /** Unique id derived from filename without extension, e.g. "char1-outfit1-chill". */
  id: string;
  /** Filename on R2, appended to baseUrl to build full URL. */
  filename: string;
  /** File size in bytes (from generation-time stat). */
  size: number;
  /** Outfit number 1-6 (corresponds to skin / clothing variant). */
  outfit: number;
  /** Activity state shown in animation. */
  state: VideoOutfitState;
};

/**
 * A single card image (front or back of a wisdom card).
 *
 * Front cards: 48 (4 categories x 12 cards each).
 * Back cards: 4 (one shared back per category).
 *
 * NOTE: cards-background.webp and save-collection.webp are UI framing
 * assets, NOT in this manifest — they live in apps/mobile/assets/images/cards/
 * and ship with the app bundle (git-tracked).
 */
export type CardManifestEntry = {
  /** Unique id derived from filename without extension. */
  id: string;
  /** Filename on R2. */
  filename: string;
  /** File size in bytes. */
  size: number;
  /** Category the card belongs to. */
  category: CardCategory;
  /** Whether this is a front (specific card) or back (category-shared). */
  type: CardType;
  /** Specific card name (e.g. "accountability"). null for back cards. */
  name: string | null;
};

export type AssetManifest = {
  /** Manifest schema version. Bump when changing structure. */
  version: ManifestVersion;
  /** R2 base URL. Append filename to get full URL. */
  baseUrl: string;
  /** Character animation videos. */
  videos: VideoManifestEntry[];
  /** Wisdom card images. */
  cards: CardManifestEntry[];
};

/**
 * State of a single asset in the local cache.
 */
export type AssetCacheStatus = 'missing' | 'downloading' | 'cached' | 'failed';

/**
 * Result of a single asset download attempt.
 */
export type AssetDownloadResult = {
  filename: string;
  status: AssetCacheStatus;
  /** Local file:// URI if cached, undefined otherwise. */
  uri?: string;
  /** Error message if status is 'failed'. */
  error?: string;
};
