-- EMERGENCY ONLY. Restores the 2026-08-28 pre-hardening access snapshot.
-- Restores previously public access; review before use. Contains no user rows.
begin;
set local lock_timeout = '2s';
set local statement_timeout = '45s';
revoke all privileges on table "public"."leaderboard_seeds" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."leaderboard_seeds" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."leaderboard_seeds" to "authenticated";
revoke all privileges on table "public"."reflect_drafts" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reflect_drafts" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reflect_drafts" to "authenticated";
revoke all privileges on table "public"."default_creators" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."default_creators" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."default_creators" to "authenticated";
revoke all privileges on table "public"."likes" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."likes" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."likes" to "authenticated";
revoke all privileges on table "public"."daily_tasks" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."daily_tasks" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."daily_tasks" to "authenticated";
revoke all privileges on table "public"."user_characters" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_characters" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_characters" to "authenticated";
revoke all privileges on table "public"."profiles" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."profiles" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."profiles" to "authenticated";
revoke all privileges on table "public"."user_stats" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_stats" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_stats" to "authenticated";
revoke all privileges on table "public"."leaderboard" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."leaderboard" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."leaderboard" to "authenticated";
revoke all privileges on table "public"."card_saves" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."card_saves" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."card_saves" to "authenticated";
revoke all privileges on table "public"."blocked_users" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."blocked_users" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."blocked_users" to "authenticated";
revoke all privileges on table "public"."reports" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reports" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reports" to "authenticated";
revoke all privileges on table "public"."seek_question_cards" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."seek_question_cards" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."seek_question_cards" to "authenticated";
revoke all privileges on table "public"."seek_questions" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."seek_questions" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."seek_questions" to "authenticated";
revoke all privileges on table "public"."listens" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."listens" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."listens" to "authenticated";
revoke all privileges on table "public"."item_learning_decisions" from public, anon, authenticated;
revoke all privileges on table "public"."support_tickets" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."support_tickets" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."support_tickets" to "authenticated";
revoke all privileges on table "public"."user_liked_wisdoms" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_liked_wisdoms" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_liked_wisdoms" to "authenticated";
revoke all privileges on table "public"."user_liked_defaults" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_liked_defaults" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_liked_defaults" to "authenticated";
revoke all privileges on table "public"."weekly_reports" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."weekly_reports" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."weekly_reports" to "authenticated";
revoke all privileges on table "public"."card_keywords" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."card_keywords" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."card_keywords" to "authenticated";
revoke all privileges on table "public"."user_read_announcements" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_read_announcements" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_read_announcements" to "authenticated";
revoke all privileges on table "public"."wisdom_comments" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_comments" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_comments" to "authenticated";
revoke all privileges on table "public"."app_config" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."app_config" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."app_config" to "authenticated";
revoke all privileges on table "public"."character_data" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."character_data" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."character_data" to "authenticated";
revoke all privileges on table "public"."app_announcements" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."app_announcements" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."app_announcements" to "authenticated";
revoke all privileges on table "public"."wisdoms" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdoms" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdoms" to "authenticated";
revoke all privileges on table "public"."wisdom_cards" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_cards" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_cards" to "authenticated";
revoke all privileges on table "public"."orders" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."orders" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."orders" to "authenticated";
revoke all privileges on table "public"."user_seen_skin_unlocks" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_seen_skin_unlocks" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_seen_skin_unlocks" to "authenticated";
revoke all privileges on table "public"."item_learning_occurrences" from public, anon, authenticated;
revoke all privileges on table "public"."item_match_removals" from public, anon, authenticated;
revoke all privileges on table "public"."wisdom_card_blocks" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_card_blocks" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_card_blocks" to "authenticated";
revoke all privileges on table "public"."book_orders" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."book_orders" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."book_orders" to "authenticated";
revoke all privileges on table "public"."wisdom_blocks" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_blocks" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_blocks" to "authenticated";
revoke all privileges on table "public"."wisdom_card_reports" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_card_reports" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."wisdom_card_reports" to "authenticated";
revoke all privileges on table "public"."disposable_email_domains" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."disposable_email_domains" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."disposable_email_domains" to "authenticated";
revoke all privileges on table "public"."force_updates" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."force_updates" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."force_updates" to "authenticated";
revoke all privileges on table "public"."item_keyword_rule_events" from public, anon, authenticated;
revoke all privileges on sequence "public"."item_keyword_rule_events_revision_seq" from public, anon, authenticated;
grant SELECT, UPDATE, USAGE on sequence "public"."item_keyword_rule_events_revision_seq" to "anon";
grant SELECT, UPDATE, USAGE on sequence "public"."item_keyword_rule_events_revision_seq" to "authenticated";
revoke all privileges on table "public"."companions" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."companions" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."companions" to "authenticated";
revoke all privileges on table "public"."companion_skins" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."companion_skins" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."companion_skins" to "authenticated";
revoke all privileges on table "public"."gem_events" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."gem_events" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."gem_events" to "authenticated";
revoke all privileges on table "public"."user_gems" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_gems" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_gems" to "authenticated";
revoke all privileges on table "public"."kit_completions" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."kit_completions" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."kit_completions" to "authenticated";
revoke all privileges on table "public"."xp_events" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."xp_events" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."xp_events" to "authenticated";
revoke all privileges on table "public"."reflects" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reflects" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reflects" to "authenticated";
revoke all privileges on table "public"."lens_cards" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."lens_cards" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."lens_cards" to "authenticated";
revoke all privileges on table "public"."lens_progress" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."lens_progress" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."lens_progress" to "authenticated";
revoke all privileges on table "public"."items" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."items" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."items" to "authenticated";
revoke all privileges on table "public"."user_items" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_items" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_items" to "authenticated";
revoke all privileges on table "public"."item_memories" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."item_memories" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."item_memories" to "authenticated";
revoke all privileges on table "public"."focus_sessions" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."focus_sessions" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."focus_sessions" to "authenticated";
revoke all privileges on table "public"."user_focus_progress" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_focus_progress" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."user_focus_progress" to "authenticated";
revoke all privileges on table "public"."skills" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."skills" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."skills" to "authenticated";
revoke all privileges on table "public"."guesses" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."guesses" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."guesses" to "authenticated";
revoke all privileges on table "public"."duo_memberships" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."duo_memberships" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."duo_memberships" to "authenticated";
revoke all privileges on table "public"."master_visits" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."master_visits" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."master_visits" to "authenticated";
revoke all privileges on table "public"."quest_plans" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."quest_plans" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."quest_plans" to "authenticated";
revoke all privileges on table "public"."bubble_pops" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."bubble_pops" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."bubble_pops" to "authenticated";
revoke all privileges on table "public"."friendships" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."friendships" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."friendships" to "authenticated";
revoke all privileges on table "public"."cosmetic_unlocks" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."cosmetic_unlocks" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."cosmetic_unlocks" to "authenticated";
revoke all privileges on table "public"."battle_progress" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."battle_progress" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."battle_progress" to "authenticated";
revoke all privileges on table "public"."friend_feed_reads" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."friend_feed_reads" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."friend_feed_reads" to "authenticated";
revoke all privileges on table "public"."shared_memory_items" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."shared_memory_items" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."shared_memory_items" to "authenticated";
revoke all privileges on table "public"."pairings" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."pairings" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."pairings" to "authenticated";
revoke all privileges on table "public"."connection_insights" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."connection_insights" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."connection_insights" to "authenticated";
revoke all privileges on table "public"."rate_limits" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."rate_limits" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."rate_limits" to "authenticated";
revoke all privileges on table "public"."good_vibes" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."good_vibes" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."good_vibes" to "authenticated";
revoke all privileges on table "public"."shared_memory_reads" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."shared_memory_reads" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."shared_memory_reads" to "authenticated";
revoke all privileges on table "public"."item_learning_candidates" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."item_learning_candidates" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."item_learning_candidates" to "authenticated";
revoke all privileges on table "public"."quest_custom_generations" from public, anon, authenticated;
revoke all privileges on table "public"."store_credential_bindings" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."store_credential_bindings" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."store_credential_bindings" to "authenticated";
revoke all privileges on table "public"."subscriptions" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."subscriptions" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."subscriptions" to "authenticated";
revoke all privileges on table "public"."reflect_items" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reflect_items" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reflect_items" to "authenticated";
revoke all privileges on sequence "public"."ai_usage_events_id_seq" from public, anon, authenticated;
grant SELECT, UPDATE, USAGE on sequence "public"."ai_usage_events_id_seq" to "anon";
grant SELECT, UPDATE, USAGE on sequence "public"."ai_usage_events_id_seq" to "authenticated";
revoke all privileges on table "public"."reflect_ai_analyses" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reflect_ai_analyses" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."reflect_ai_analyses" to "authenticated";
revoke all privileges on table "public"."connection_update_candidates" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."connection_update_candidates" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."connection_update_candidates" to "authenticated";
revoke all privileges on table "public"."weekly_recaps" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."weekly_recaps" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."weekly_recaps" to "authenticated";
revoke all privileges on table "public"."ai_usage_events" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."ai_usage_events" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."ai_usage_events" to "authenticated";
revoke all privileges on table "public"."connection_card_history" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."connection_card_history" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."connection_card_history" to "authenticated";
revoke all privileges on table "public"."item_learning_jobs" from public, anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."item_learning_jobs" to "anon";
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table "public"."item_learning_jobs" to "authenticated";
revoke all privileges on function public.match_wisdoms(vector,text[],integer,double precision) from public, anon, authenticated;
grant EXECUTE on function public.match_wisdoms(vector,text[],integer,double precision) to public;
grant EXECUTE on function public.match_wisdoms(vector,text[],integer,double precision) to "anon";
grant EXECUTE on function public.match_wisdoms(vector,text[],integer,double precision) to "authenticated";
alter function public.match_wisdoms(vector,text[],integer,double precision) reset search_path;
revoke all privileges on function public.increment_unread_feedback(uuid) from public, anon, authenticated;
grant EXECUTE on function public.increment_unread_feedback(uuid) to public;
grant EXECUTE on function public.increment_unread_feedback(uuid) to "anon";
grant EXECUTE on function public.increment_unread_feedback(uuid) to "authenticated";
alter function public.increment_unread_feedback(uuid) reset search_path;
revoke all privileges on function public.handle_new_user_subscription() from public, anon, authenticated;
grant EXECUTE on function public.handle_new_user_subscription() to public;
grant EXECUTE on function public.handle_new_user_subscription() to "anon";
grant EXECUTE on function public.handle_new_user_subscription() to "authenticated";
revoke all privileges on function public.handle_new_user() from public, anon, authenticated;
grant EXECUTE on function public.handle_new_user() to public;
grant EXECUTE on function public.handle_new_user() to "anon";
grant EXECUTE on function public.handle_new_user() to "authenticated";
alter function public.handle_new_user() reset search_path;
revoke all privileges on function public.broadcast_connection_insight_change() from public, anon, authenticated;
grant EXECUTE on function public.broadcast_connection_insight_change() to public;
grant EXECUTE on function public.broadcast_connection_insight_change() to "anon";
grant EXECUTE on function public.broadcast_connection_insight_change() to "authenticated";
revoke all privileges on function public.apply_connection_insight_updates_v2(uuid,uuid,uuid,date,uuid,jsonb) from public, anon, authenticated;
revoke all privileges on function public.begin_saved_reflect(uuid,jsonb,jsonb,integer,text) from public, anon, authenticated;
revoke all privileges on function public.checkpoint_reflect_settlement(uuid,uuid,jsonb,bigint) from public, anon, authenticated;
revoke all privileges on function public.store_reflect_generation(uuid,uuid,jsonb,text) from public, anon, authenticated;
revoke all privileges on function public.complete_saved_reflect(uuid,uuid,jsonb,bigint) from public, anon, authenticated;
revoke all privileges on function public.edit_durable_reflect_memories(uuid,uuid,jsonb) from public, anon, authenticated;
revoke all privileges on function public.update_wisdom_likes_count() from public, anon, authenticated;
grant EXECUTE on function public.update_wisdom_likes_count() to public;
grant EXECUTE on function public.update_wisdom_likes_count() to "anon";
grant EXECUTE on function public.update_wisdom_likes_count() to "authenticated";
alter function public.update_wisdom_likes_count() reset search_path;
revoke all privileges on function public.update_wisdom_listens_count() from public, anon, authenticated;
grant EXECUTE on function public.update_wisdom_listens_count() to public;
grant EXECUTE on function public.update_wisdom_listens_count() to "anon";
grant EXECUTE on function public.update_wisdom_listens_count() to "authenticated";
alter function public.update_wisdom_listens_count() reset search_path;
revoke all privileges on function public.finalize_reflect_draft(uuid,uuid,jsonb,jsonb,integer,text) from public, anon, authenticated;
revoke all privileges on function public.broadcast_shared_box_change(uuid) from public, anon, authenticated;
revoke all privileges on function public.assign_seek_question_display_order() from public, anon, authenticated;
grant EXECUTE on function public.assign_seek_question_display_order() to public;
grant EXECUTE on function public.assign_seek_question_display_order() to "anon";
grant EXECUTE on function public.assign_seek_question_display_order() to "authenticated";
alter function public.assign_seek_question_display_order() reset search_path;
revoke all privileges on function public.apply_store_subscription(uuid,text,text,text,text,timestamp with time zone,text,text,text,text,text,text,boolean) from public, anon, authenticated;
revoke all privileges on function public.item_rule_snapshot(text,bigint) from public, anon, authenticated;
revoke all privileges on function public.publish_item_rule(text,text,text,text,bigint,uuid,uuid,uuid) from public, anon, authenticated;
revoke all privileges on function public.claim_item_learning_jobs() from public, anon, authenticated;
revoke all privileges on function public.record_item_learning_evidence(uuid,text,text,text,text,numeric,boolean) from public, anon, authenticated;
revoke all privileges on function public.check_disposable_email(jsonb) from public, anon, authenticated;
revoke all privileges on function public.insert_wisdom_card_if_under_quota(uuid,timestamp with time zone,integer,jsonb) from public, anon, authenticated;
revoke all privileges on function public.record_skill(uuid,uuid,dimension_t,text,text,skill_rarity) from public, anon, authenticated;
revoke all privileges on function public.clamp_companion_xp() from public, anon, authenticated;
grant EXECUTE on function public.clamp_companion_xp() to public;
grant EXECUTE on function public.clamp_companion_xp() to "anon";
grant EXECUTE on function public.clamp_companion_xp() to "authenticated";
alter function public.clamp_companion_xp() reset search_path;
revoke all privileges on function public.submit_kit(uuid,kit_t,xp_source,text,date,text,integer,jsonb,jsonb) from public, anon, authenticated;
revoke all privileges on function public.complete_onboarding(uuid,companion_t) from public, anon, authenticated;
revoke all privileges on function public.record_item_matches(uuid,uuid,jsonb,date) from public, anon, authenticated;
revoke all privileges on function public.pop_bubble(uuid,uuid,text,date,text,integer,integer) from public, anon, authenticated;
revoke all privileges on function public.record_tame_points(uuid,integer,date,text,integer,integer) from public, anon, authenticated;
revoke all privileges on function public.unset_pairing(uuid) from public, anon, authenticated;
revoke all privileges on function public.submit_reflect(uuid,smallint,text,date,text,integer,jsonb,kit_t,boolean,text) from public, anon, authenticated;
revoke all privileges on function public.set_pairing(uuid,uuid,text,date) from public, anon, authenticated;
revoke all privileges on function public.next_lens_card(uuid,text) from public, anon, authenticated;
revoke all privileges on function public.submit_lens(uuid,text,uuid,integer,text,date,text,integer) from public, anon, authenticated;
revoke all privileges on function public.record_wisdom_usage(uuid,integer) from public, anon, authenticated;
alter function public.record_wisdom_usage(uuid,integer) reset search_path;
revoke all privileges on function public.can_user_record(uuid) from public, anon, authenticated;
alter function public.can_user_record(uuid) reset search_path;
revoke all privileges on function public.check_rate_limit(text,integer,integer) from public, anon, authenticated;
revoke all privileges on function public.release_pair_plus_entitlements(uuid,uuid) from public, anon, authenticated;
revoke all privileges on function public.release_entitlement_after_pairing_delete() from public, anon, authenticated;
grant EXECUTE on function public.release_entitlement_after_pairing_delete() to public;
grant EXECUTE on function public.release_entitlement_after_pairing_delete() to "anon";
grant EXECUTE on function public.release_entitlement_after_pairing_delete() to "authenticated";
revoke all privileges on function public.sync_entitlement_after_subscription_change() from public, anon, authenticated;
grant EXECUTE on function public.sync_entitlement_after_subscription_change() to public;
grant EXECUTE on function public.sync_entitlement_after_subscription_change() to "anon";
grant EXECUTE on function public.sync_entitlement_after_subscription_change() to "authenticated";
revoke all privileges on function public.accept_pairing_invitation(uuid,uuid) from public, anon, authenticated;
revoke all privileges on function public.broadcast_good_vibe_insert() from public, anon, authenticated;
grant EXECUTE on function public.broadcast_good_vibe_insert() to public;
grant EXECUTE on function public.broadcast_good_vibe_insert() to "anon";
grant EXECUTE on function public.broadcast_good_vibe_insert() to "authenticated";
revoke all privileges on function public.has_own_active_plus(uuid) from public, anon, authenticated;
revoke all privileges on function public.check_quest_task(uuid,integer,date,text,integer,integer) from public, anon, authenticated;
revoke all privileges on function public.sync_entitlement_after_pairing_insert() from public, anon, authenticated;
grant EXECUTE on function public.sync_entitlement_after_pairing_insert() to public;
grant EXECUTE on function public.sync_entitlement_after_pairing_insert() to "anon";
grant EXECUTE on function public.sync_entitlement_after_pairing_insert() to "authenticated";
revoke all privileges on function public.sync_pair_plus_entitlements(uuid,uuid) from public, anon, authenticated;
revoke all privileges on function public.broadcast_entitlement_change() from public, anon, authenticated;
grant EXECUTE on function public.broadcast_entitlement_change() to public;
grant EXECUTE on function public.broadcast_entitlement_change() to "anon";
grant EXECUTE on function public.broadcast_entitlement_change() to "authenticated";
revoke all privileges on function public.expire_store_subscription(uuid,text,timestamp with time zone) from public, anon, authenticated;
revoke all privileges on function public.broadcast_pairing_change() from public, anon, authenticated;
grant EXECUTE on function public.broadcast_pairing_change() to public;
grant EXECUTE on function public.broadcast_pairing_change() to "anon";
grant EXECUTE on function public.broadcast_pairing_change() to "authenticated";
revoke all privileges on function public.submit_tame_enemy(uuid,text,date,text,integer,jsonb,integer,integer,integer) from public, anon, authenticated;
revoke all privileges on function public.broadcast_friendship_invitation() from public, anon, authenticated;
grant EXECUTE on function public.broadcast_friendship_invitation() to public;
grant EXECUTE on function public.broadcast_friendship_invitation() to "anon";
grant EXECUTE on function public.broadcast_friendship_invitation() to "authenticated";
revoke all privileges on function public.broadcast_shared_box_insert() from public, anon, authenticated;
grant EXECUTE on function public.broadcast_shared_box_insert() to public;
grant EXECUTE on function public.broadcast_shared_box_insert() to "anon";
grant EXECUTE on function public.broadcast_shared_box_insert() to "authenticated";
revoke all privileges on function public.finalize_reflect_draft_legacy(uuid,uuid,jsonb,jsonb,integer,text) from public, anon, authenticated;
revoke all privileges on function public.submit_true_north(uuid,text,date,text,integer,jsonb,jsonb) from public, anon, authenticated;
revoke all privileges on function public.edit_reflect_item_memories(uuid,uuid,jsonb) from public, anon, authenticated;
revoke all privileges on function public.broadcast_reflect_feed_change(uuid) from public, anon, authenticated;
revoke execute on function public.handle_new_user() from supabase_auth_admin;
revoke execute on function public.handle_new_user_subscription() from supabase_auth_admin;
alter view public.user_stats reset (security_invoker);
alter view public.leaderboard reset (security_invoker);
drop policy if exists "Anyone can insert listens" on public.listens;
create policy "Anyone can insert listens" on public.listens for insert to public with check (true);
alter default privileges for role postgres in schema public revoke all privileges on tables from public, anon, authenticated;
alter default privileges for role postgres in schema public revoke all privileges on sequences from public, anon, authenticated;
alter default privileges for role postgres in schema public revoke all privileges on functions from public, anon, authenticated;
alter default privileges for role postgres revoke execute on functions from public, anon, authenticated;
alter default privileges for role postgres in schema "public" grant SELECT, UPDATE, USAGE on sequences to "anon";
alter default privileges for role postgres in schema "public" grant SELECT, UPDATE, USAGE on sequences to "authenticated";
alter default privileges for role postgres in schema "public" grant EXECUTE on functions to "anon";
alter default privileges for role postgres in schema "public" grant EXECUTE on functions to "authenticated";
alter default privileges for role postgres in schema "public" grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on tables to "anon";
alter default privileges for role postgres in schema "public" grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on tables to "authenticated";
alter default privileges for role postgres grant execute on functions to public;
delete from supabase_migrations.schema_migrations where version = '20260828000070';
notify pgrst, 'reload schema';
commit;
