#!/usr/bin/env python3
"""Plan a deletion in reverse topological order.

Given a set of seed files, answers three questions the compiler will not:

  1. Which surviving files still *import* into the deletion set?
     Fix those before `git rm`, or type-check drowns in cascading errors and
     stops working as a checkpoint.

  2. Which files become unreachable once the seeds are gone?
     Applied repeatedly: a file whose last importer died is dead too.

  3. Which surviving files still *navigate to* a deleted route?
     expo-router resolves `router.push('/seek-question')` and
     `<Tabs.Screen name="discover" />` by string, at runtime. Those are zero
     edges in any import graph. And because app.json sets
     `experiments.typedRoutes` while tsconfig includes `.expo/types/**`, the
     route union that would have caught it is regenerated by the Metro dev
     server -- not by `tsc --noEmit`. So type-check passes on a stale file and
     the tab silently goes blank. This scan is the only thing standing there.

Route files under apps/mobile/app/ are never auto-orphaned: expo-router loads
them by path, so they have no importers by construction. Treating "nobody
imports it" as "it is dead" would condemn every screen in the app.

Usage:
    python3 tools/depgraph.py
    python3 tools/plan-delete.py seeds.txt
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

# File-system routers load these by path, never by import, so they have no
# importers by construction. Treating "nobody imports it" as "it is dead" would
# condemn every screen and every endpoint in the repo.
ROUTES = ('apps/mobile/app/', 'apps/api/src/app/')

# Stems too generic to search for as route strings. `index` and `_layout` are
# structural names, not destinations.
GENERIC_STEMS = {'index', '_layout'}


def lines_of(p: str) -> int:
    return len(Path(p).read_text(encoding='utf-8').splitlines())


# Set by main() from --classes, so the protected set and the dangling-import
# grouping read the SAME classification the seeds came from. Hardcoding the
# mobile file here is exactly why the api run mis-grouped ai.js and me-stats:
# it was reading a classification for a different set of files.
_CLASSES_PATH = 'tools/v2-classification.txt'


def read_classes() -> dict:
    """path -> DELETE | REWRITE | KEEP, from the active classification file."""
    f = Path(_CLASSES_PATH)
    if not f.exists():
        return {}
    out = {}
    for line in f.read_text(encoding='utf-8').splitlines():
        line = line.split('#')[0].strip()
        if line:
            tag, path = line.split(None, 1)
            out[path] = tag
    return out


def cascade_from(seeds, files, imported_by, protected):
    """Peel leaves: a file whose last importer died is dead too.

    Two exemptions, for opposite reasons.

    Route files under apps/mobile/app/ have no importers by construction --
    expo-router loads them by path. "Nobody imports it" would condemn every
    screen.

    KEEP files are infrastructure that v2.0 will import again. toast.tsx and
    relative-time.ts are orphaned the moment v1 dies, but Bags needs a toast
    for "+3 items" and Friends needs "5m ago". The graph sees the present;
    the classification file states the intent. Deleting them and writing them
    again in three weeks is not a saving.
    """
    doomed = set(seeds)
    while True:
        newly = {
            f for f in files - doomed
            if not f.startswith(ROUTES)
            and f not in protected
            and f in imported_by
            and not (imported_by[f] - doomed)
        }
        if not newly:
            break
        doomed |= newly
    return doomed


def dangling_imports(doomed, files, imports):
    out = {}
    for f in files - doomed:
        hits = imports.get(f, set()) & doomed
        if hits:
            out[f] = sorted(hits)
    return out


def dangling_routes(doomed, files):
    """String references to a deleted route, in any surviving file."""
    # Route stems only mean something for expo-router, where a screen file's name
    # IS its URL segment. Next.js names every endpoint file `route.js` and puts
    # the URL in the directory, so its stems are all the same word.
    stems = {
        Path(f).stem: f
        for f in doomed
        if f.startswith('apps/mobile/app/') and Path(f).stem not in GENERIC_STEMS
    }

    # Route GROUPS are navigable too. `router.replace('/(onboarding)')` targets
    # the group's index route, and if every file in the group is being deleted
    # the group itself stops existing. The stem patterns below all require a
    # segment after the group name, so this slipped through Phase A: tsc caught
    # it, but only because the new router.d.ts had already dropped the group.
    # In the other direction -- a stale union that still lists it -- nothing
    # would have caught it before runtime.
    groups = defaultdict(lambda: [set(), set()])
    for f in files:
        if not f.startswith('apps/mobile/app/'):
            continue
        for part in Path(f).parts:
            if part.startswith('(') and part.endswith(')'):
                groups[part][0].add(f)
                if f in doomed:
                    groups[part][1].add(f)
    for group, (members, dead) in groups.items():
        if members and members == dead:
            stems[group] = 'route group ' + group
    # expo-router references a route in exactly two shapes. Anything else that
    # merely contains the stem is noise -- and noise is not free: a check that
    # reports 37 hits of which 19 are `require('../../assets/logo.png')` teaches
    # everyone to skim past the 7 that matter.
    #
    #   1. <Tabs.Screen name="discover" />        JSX name prop
    #   2. router.push('/(main)/record')          absolute route path, starts '/('
    #      pathname: '/(main)/(modals)/x'
    #
    # Relative requires, API paths, and asset folders share stems with routes by
    # coincidence. `assets` is a tab AND a directory; `record` is a screen AND a
    # verb. Only the two shapes above are navigation.
    global PATTERNS
    PATTERNS = {
        stem: (
            [re.compile(rf"""['"]/{re.escape(stem)}['"]""")]
            if stem.startswith('(')
            else [
                re.compile(rf"""\bname=["']{re.escape(stem)}["']"""),
                re.compile(rf"""['"]/\([^'"]*/{re.escape(stem)}(?=['"/])"""),
                re.compile(rf"""['"]/\([^'"]*/{re.escape(stem)}['"]"""),
            ]
        )
        for stem in stems
    }
    hits = defaultdict(list)
    for f in sorted(files - doomed):
        for i, line in enumerate(Path(f).read_text(encoding='utf-8').splitlines(), 1):
            for stem in stems:
                for pat in PATTERNS[stem]:
                    if pat.search(line):
                        hits[stem].append((f, i, line.strip()))
                        break
    return stems, hits


def main(seed_file: str, classes_path: str) -> int:
    global _CLASSES_PATH
    _CLASSES_PATH = classes_path
    graph = json.loads(Path('/tmp/novame-graph.json').read_text())
    files = set(graph['files'])
    imports = {k: set(v) for k, v in graph['imports'].items()}
    imported_by = {k: set(v) for k, v in graph['importedBy'].items()}

    seeds = [l.strip() for l in Path(seed_file).read_text().splitlines()
             if l.strip() and not l.startswith('#')]

    unknown = [s for s in seeds if s not in files]
    if unknown:
        print('!! not in graph (typo? already deleted? stale graph?):')
        for u in unknown:
            print(f'   {u}')
        return 1

    classes = read_classes()
    protected = {f for f, t in classes.items() if t in ('KEEP', 'REWRITE')}
    doomed = cascade_from(seeds, files, imported_by, protected)
    cascade = doomed - set(seeds)

    stranded = sorted(
        f for f in files - doomed
        if f in protected and not f.startswith(ROUTES)
        and f in imported_by and not (imported_by[f] - doomed)
    )
    dang_imp = dangling_imports(doomed, files, imports)
    stems, dang_route = dangling_routes(doomed, files)

    total = sum(lines_of(f) for f in doomed)
    print(f'seeds        {len(seeds):3}')
    print(f'cascade      {len(cascade):3}  (become unreachable)')
    print(f'total        {len(doomed):3} files, {total} lines')
    print()

    if cascade:
        print('--- cascade (delete these too):')
        for f in sorted(cascade):
            print(f'   {f:66} {lines_of(f):5} lines')
        print()

    if stranded:
        print(f'--- {len(stranded)} protected file(s) will have zero importers.')
        print('    Not dead -- waiting for v2.0 to import them again.\n')
        for f in stranded:
            print(f'   {f:66} {lines_of(f):5} lines')
        print()

    if dang_imp:
        # Split by the classification of the *importer*. A REWRITE file pointing
        # into the deletion set is expected -- its body is being replaced anyway.
        # A KEEP file pointing into it means the classification is wrong: that
        # file is entangled with a v1 concept and cannot survive untouched.
        # A KEEP file, or an unclassified one, importing into the deletion set is
        # a hard error: KEEP must compile untouched, and "unclassified" means a
        # file nobody reasoned about is pointing at something about to vanish.
        # Only REWRITE files are allowed to dangle -- their bodies are being
        # replaced anyway.
        hard = {f: h for f, h in dang_imp.items() if classes.get(f) != 'REWRITE'}
        soft = {f: h for f, h in dang_imp.items() if classes.get(f) == 'REWRITE'}

        if hard:
            print(f'--- HARD ERROR: {len(hard)} surviving file(s) import into the set.')
            print('    KEEP files must compile untouched; unclassified files were')
            print('    never reasoned about. Reclassify, or sever the dependency.\n')
            for f, hits in sorted(hard.items()):
                cls_label = classes.get(f, 'UNCLASSIFIED')
                print(f'   [{cls_label}] {f}')
                for h in hits:
                    print(f'       -> {h}')
            print()
        if soft:
            print(f'--- {len(soft)} REWRITE file(s) import into the set (expected):')
            for f, hits in sorted(soft.items()):
                print(f'   {f:58} -> {len(hits)} dep(s)')
            print()
    else:
        print('--- no dangling imports')

    classes_for_routes = read_classes()
    keep_routes = {
        stem: [(f, i, l) for f, i, l in hits if classes_for_routes.get(f) == 'KEEP']
        for stem, hits in dang_route.items()
    }
    keep_routes = {k: v for k, v in keep_routes.items() if v}

    if stems:
        print(f'--- route names to check ({len(stems)}): {", ".join(sorted(stems))}')
    if dang_route:
        n = sum(len(v) for v in dang_route.values())
        print(f'--- !! {n} surviving reference(s) to a DELETED ROUTE.')
        print('    The import graph cannot see these. Fix before git rm.')
        for stem, hits in sorted(dang_route.items()):
            print(f'\n    route "{stem}"  (from {stems[stem]})')
            for f, i, line in hits:
                print(f'       {f}:{i}')
                print(f'         {line[:96]}')
        print()
    else:
        print('--- no dangling route references')

    if keep_routes:
        n = sum(len(v) for v in keep_routes.values())
        print(f'--- HARD ERROR: {n} route reference(s) live in KEEP files.')
        print('    A KEEP file must compile and run untouched. Navigating to a')
        print('    deleted route does neither. Reclassify as REWRITE.')
        print()
        for stem, hits in sorted(keep_routes.items()):
            for f, i, l in hits:
                print(f'   {f}:{i}  -> "{stem}"')
        print()

    classes_all = read_classes()
    hard_dangling = {f for f in dang_imp if classes_all.get(f) != 'REWRITE'}
    blocked = bool(hard_dangling or dang_route or keep_routes)
    print()
    if blocked:
        print('BLOCKED. Resolve the above, re-run tools/depgraph.py, then re-plan.')
        return 2

    print('--- git rm command:')
    quoted = " \\\n          ".join(f"'{f}'" for f in sorted(doomed))
    print(f'git rm -q {quoted}')
    return 0


if __name__ == '__main__':
    if len(sys.argv) not in (2, 3):
        print(__doc__)
        print('\nusage: plan-delete.py SEEDS [CLASSIFICATION]')
        sys.exit(1)
    seeds = sys.argv[1]
    classes = sys.argv[2] if len(sys.argv) == 3 else 'tools/v2-classification.txt'
    sys.exit(main(seeds, classes))
