#!/usr/bin/env python3
"""
Slice every memory item out of its standardized sprite sheet into an
individual 256x256 webp, and generate the require() map the app uses to
render them (2026-07-30 perf pass — per-item files decode in ~1ms and are
cached independently by expo-image, killing the one-by-one pop-in that
whole-sheet decoding caused in Bags / Guided / Object Reflect).

Inputs:
  packages/engine/src/items/dictionary.json      (sheetId, row, col per item)
  apps/mobile/assets/items/<sheetId>.webp        (8-col standardized sheets)

Outputs:
  apps/mobile/assets/items/each/<itemId>.webp    (one 256px webp per item)
  apps/mobile/src/lib/item-images.g.ts           (GENERATED require map)

Run after every dictionary/sheet regeneration:
  python3 tools/slice-item-images.py
"""
import json
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DICT_PATH = os.path.join(ROOT, 'packages/engine/src/items/dictionary.json')
SHEETS_DIR = os.path.join(ROOT, 'apps/mobile/assets/items')
OUT_DIR = os.path.join(SHEETS_DIR, 'each')
GEN_TS = os.path.join(ROOT, 'apps/mobile/src/lib/item-images.g.ts')

COLS = 8
CELL = 256


def main() -> int:
    data = json.load(open(DICT_PATH))
    items = data['items']
    os.makedirs(OUT_DIR, exist_ok=True)

    sheets: dict[str, Image.Image] = {}
    sliced: list[str] = []
    skipped: list[str] = []
    total_bytes = 0

    for item_id in sorted(items):
        it = items[item_id]
        sheet_id = it.get('sheetId')
        row, col = it.get('row'), it.get('col')
        if not sheet_id or row is None or col is None:
            skipped.append(item_id)
            continue
        if sheet_id not in sheets:
            path = os.path.join(SHEETS_DIR, f'{sheet_id}.webp')
            if not os.path.exists(path):
                skipped.append(item_id)
                continue
            sheets[sheet_id] = Image.open(path).convert('RGBA')
        sheet = sheets[sheet_id]
        cell = sheet.width // COLS  # 256 for the current batch
        box = (col * cell, row * cell, (col + 1) * cell, (row + 1) * cell)
        if box[3] > sheet.height or box[2] > sheet.width:
            skipped.append(item_id)
            continue
        tile = sheet.crop(box)
        if cell != CELL:
            tile = tile.resize((CELL, CELL), Image.LANCZOS)
        out = os.path.join(OUT_DIR, f'{item_id}.webp')
        tile.save(out, 'WEBP', quality=88, method=6)
        total_bytes += os.path.getsize(out)
        sliced.append(item_id)

    lines = [
        '/**',
        ' * GENERATED by tools/slice-item-images.py — DO NOT EDIT.',
        ' * One 256px webp per memory item; ItemSprite renders these directly',
        ' * so each tile decodes only its own few-KB file (no sheet decoding).',
        f' * {len(sliced)} items. Re-run the script after dictionary changes.',
        ' */',
        '',
        'export const ITEM_IMAGES: Record<string, number> = {',
    ]
    for item_id in sliced:
        lines.append(f"  '{item_id}': require('../../assets/items/each/{item_id}.webp'),")
    lines.append('};')
    lines.append('')
    open(GEN_TS, 'w').write('\n'.join(lines))

    print(f'sliced {len(sliced)} items from {len(sheets)} sheets '
          f'({total_bytes / 1024 / 1024:.1f} MB total)')
    if skipped:
        print(f'skipped {len(skipped)}: {skipped[:8]}{"…" if len(skipped) > 8 else ""}')
    print(f'wrote {os.path.relpath(GEN_TS, ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
